FROM archlinux/base

RUN pacman --noconfirm --sync --refresh sudo && \
    groupadd nopasswd-sudoers && \
    echo '%nopasswd-sudoers ALL=(ALL) NOPASSWD: ALL' >/etc/sudoers.d/nopasswd-sudoers && \
    useradd tester \
    --user-group \
    --create-home \
    --home-dir /home/tester \
    --groups nopasswd-sudoers
RUN sudo pacman --noconfirm --sync \
    automake \
    awk \
    binutils \
    coreutils \
    fakeroot \
    file \
    gcc \
    git \
    make \
    procps \
    python \
    sudo \
    which
USER tester
COPY . .
RUN ./install-tmux-from-source.sh
